In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
train_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/train.csv"
train = pd.read_csv(train_url) #training set
test_url = "http://s3.amazonaws.com/assets.datacamp.com/course/Kaggle/test.csv"
test = pd.read_csv(test_url) #test set

In [3]:
train.head()


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
train.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [6]:
test.describe()

PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  332.000000  418.000000  418.000000  417.000000
mean   1100.500000    2.265550   30.272590    0.447368    0.392344   35.627188
std     120.810458    0.841838   14.181209    0.896760    0.981429   55.907576
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   21.000000    0.000000    0.000000    7.895800
50%    1100.500000    3.000000   27.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   39.000000    1.000000    0.000000   31.500000
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [7]:
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
train.loc[train["Embarked"] == "S", "Embarked"] = 0
train.loc[train["Embarked"] == "C", "Embarked"] = 1
train.loc[train["Embarked"] == "Q", "Embarked"] = 2
train.loc[train["Sex"] == "male", "Sex"] = 0
train.loc[train["Sex"] == "female", "Sex"] = 1

test.loc[test["Embarked"] == "S", "Embarked"] = 0
test.loc[test["Embarked"] == "C", "Embarked"] = 1
test.loc[test["Embarked"] == "Q", "Embarked"] = 2
test.loc[test["Sex"] == "male", "Sex"] = 0
test.loc[test["Sex"] == "female", "Sex"] = 1

In [9]:
train["Age"] = train["Age"].fillna(train["Age"].mean())
train["Embarked"] = train["Embarked"].fillna(train["Embarked"].mode().iloc[0])
test["Age"] = test["Age"].fillna(train["Age"].mode().iloc[0])
test["Embarked"] = test["Embarked"].fillna(test["Embarked"].mode().iloc[0])


In [10]:
test.head()

PassengerId  Pclass                                          Name  Sex  \
0          892       3                              Kelly, Mr. James    0   
1          893       3              Wilkes, Mrs. James (Ellen Needs)    1   
2          894       2                     Myles, Mr. Thomas Francis    0   
3          895       3                              Wirz, Mr. Albert    0   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)    1   

    Age  SibSp  Parch   Ticket     Fare Cabin  Embarked  
0  34.5      0      0   330911   7.8292   NaN         2  
1  47.0      1      0   363272   7.0000   NaN         0  
2  62.0      0      0   240276   9.6875   NaN         2  
3  27.0      0      0   315154   8.6625   NaN         0  
4  22.0      1      1  3101298  12.2875   NaN         0

In [11]:
data = np.array(train[["Pclass","Sex","Age","Embarked"]].values)
print(data.shape)
print(data)

(891, 4)
[[ 3.          0.         22.          0.        ]
 [ 1.          1.         38.          1.        ]
 [ 3.          1.         26.          0.        ]
 ...
 [ 3.          1.         29.69911765  0.        ]
 [ 1.          0.         26.          1.        ]
 [ 3.          0.         32.          2.        ]]


In [12]:
a = np.array([[1,1,1],[2,2,2]])
# b = np.array([[1,2],[3,4],[5,6]])
c = np.array([[2],[5]])
print(a)
a =np.random.shuffle(a)
print(a)
# print(a)
# print(np.sum(a,axis=0))
# print(c)
# print(np.multiply(c,a))
# x = np.array([[1],[0],[0],[1]])
# y = np.array([[1],[1],[1],[1]])
# print((x == y).sum())

[[1 1 1]
 [2 2 2]]
None


In [13]:
data = np.array(train[["Pclass","Sex","Age","Embarked"]].values, dtype = float)
train_y = np.array(train[["Survived"]].values, dtype = float)

In [14]:
def calc_loss(res, sol):
    loss = sol - res
#     print('loss: ', np.sum(loss)/res.shape[0])
    return loss
def forward(_input, w):
#     print("check nan: ", np.isnan(np.min(_input)))
    return np.matmul(_input, w)
def backprop(_input, res, sol, w, r):
#     print('before: ',w)
    losses = calc_loss(res, sol)
    losses = np.multiply(losses, _input) # _input must already have 1 appended
    delta = np.ndarray((1,losses.shape[1]))
    delta[:,:] = np.sum(losses, axis=0)
    delta /= res.shape[0]
    delta *= r
#     print(delta.transpose())
    w += delta.transpose()
#     print('after: ',w)
def predict(res):
    res[res >= 0.5] = 1
    res[res < 0.5] = 0
    return res
def calc_acc(res,sol):
    equal_amount = (res == sol).sum()
    return equal_amount / sol.shape[0]

In [35]:
def linearRegression(train, test):
    train_x = np.array(train[["Pclass","Sex","Age","Embarked"]].values, dtype = float)
    train_y = np.array(train[["Survived"]].values, dtype = float)
    test_x = np.array(test[["Pclass","Sex","Age","Embarked"]].values, dtype = float)
    #hyperparameters
    batch_size = data.shape[0] // 2
    epochs = 1000
    r = 0.001
    #parameters
    index = 0
#     w = np.random.rand(data.shape[1] + 1,1)
    w = np.random.random((data.shape[1] + 1,1))
#     w = np.ones((data.shape[1] + 1,1))
#     w = np.ones((data.shape[1] + 1,1)) * 0.5
    print(train_x.shape)
    train_x = np.append(np.ones((train_x.shape[0],1)), train_x,axis=1)
    print(train_x.shape)
    for i in range(epochs):
        print("epoch: ", i)
        if(i == 100): r = 0.0001
        if(i == 300): r = 0.00001
        if(i == 400): r = 0.000001
        if(i == 600): r = 0.0000001
        if(i == 800): r = 0.0000001
        while(True):
            if(index + batch_size <= train_x.shape[0]):
                batch = train_x[index : index + batch_size, :]
                sol = train_y[index : index + batch_size, :]
            else:
                batch = train_x[index :, :]
                sol = train_y[index :, :]
            index += batch_size

            res = forward(batch,w)
            pred = predict(res)
            print('acc: ',calc_acc(pred, sol))
            backprop(batch, res, sol, w, r)
            
            if(index >= train_x.shape[0]):
                break
        
        index = 0
    return w

In [36]:
w = linearRegression(train,test)

(891, 4)
(891, 5)
epoch:  0
acc:  0.39101123595505616
acc:  0.3775280898876405
acc:  0.0
epoch:  1
acc:  0.39101123595505616
acc:  0.3775280898876405
acc:  0.0
epoch:  2
acc:  0.39101123595505616
acc:  0.3775280898876405
acc:  0.0
epoch:  3
acc:  0.39101123595505616
acc:  0.3775280898876405
acc:  0.0
epoch:  4
acc:  0.39101123595505616
acc:  0.3775280898876405
acc:  0.0
epoch:  5
acc:  0.39101123595505616
acc:  0.3775280898876405
acc:  0.0
epoch:  6
acc:  0.39101123595505616
acc:  0.3775280898876405
acc:  0.0
epoch:  7
acc:  0.39101123595505616
acc:  0.3775280898876405
acc:  0.0
epoch:  8
acc:  0.39101123595505616
acc:  0.3775280898876405
acc:  0.0
epoch:  9
acc:  0.39101123595505616
acc:  0.37303370786516854
acc:  0.0
epoch:  10
acc:  0.3887640449438202
acc:  0.37303370786516854
acc:  0.0
epoch:  11
acc:  0.6629213483146067
acc:  0.6651685393258427
acc:  0.0
epoch:  12
acc:  0.6606741573033708
acc:  0.6494382022471911
acc:  0.0
epoch:  13
acc:  0.6224719101123596
acc:  0.6471910112359

In [37]:
print(w)

[[ 0.38046278]
 [-0.08258968]
 [ 0.46439612]
 [-0.01302624]
 [ 0.39204651]]


In [38]:
def linearRegressionTest(w, train):
    train_x = np.array(train[["Pclass","Sex","Age","Embarked"]].values, dtype = float)
    train_y = np.array(train[["Survived"]].values, dtype = float)
    train_x = np.append(np.ones((train_x.shape[0],1)), train_x,axis=1)
    res = forward(train_x,w)
    pred = predict(res)
    print(calc_acc(pred, train_y))
#     print(res)
#     print(pred)

In [39]:
linearRegressionTest(w, train)

0.6801346801346801


In [46]:
def linearRegressionDo(w, data):
    data_x = np.array(data[["Pclass","Sex","Age","Embarked"]].values, dtype = float)
    data_x = np.append(np.ones((data_x.shape[0],1)), data_x,axis=1)
    pass_id = np.array(data[["PassengerId"]].values, dtype = int)
    res = forward(data_x,w)
    pred = predict(res).astype(int)
    output = np.append(pass_id,pred,axis=1)
    return output

In [ ]:
pred = linearRegressionDo(w, test)
print(pred.shape)
print(pred)

In [53]:
import numpy
numpy.savetxt("bone.csv", pred, delimiter=",", dtype=int)

TypeError: savetxt() got an unexpected keyword argument 'dtype'

In [55]:
with open("resultTR.csv", "wb") as f:
    f.write(b'PassengerId,Survived\n')
    numpy.savetxt(f, pred.astype(int), fmt='%i', delimiter=",")